---
title: Tijdschrift
hero_image: images/magazine.png
theme: rood
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Maak een website van een tijdschrift met meerdere pagina's.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Titel en achtergrond
  - 
    title: Maak kolommen
  - 
    title: Stijl de tijdschrift onderdelen
  - 
    title: 'Uitdaging: Voeg onderdelen aan de linker kolom toe'
  - 
    title: Voeg een tweede pagina toe
  - 
    title: 'Uitdaging: Voeg een link naar de eerste pagina toe'
  - 
    title: 'Uitdaging: Vul je tweede pagina'
  - 
    title: Voeg een animatie toe
  - 
    title: 'Uitdaging: Voeg nog een animatie toe'
