title: Magazine
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
description: Create a multi-page magazine website.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introduction
- title: Heading and Background
- title: Creating Columns
- title: Style magazine items
- title: 'Challenge: Add items to the left column'
- title: Add a second page
- title: 'Challenge: Add a link back to the first page'
- title: 'Challenge: Fill in your second page'
- title: Add an animation
- title: 'Challenge: Add another animation'

