---
title: Tạp chí
hero_image: hình ảnh / tạp chí.png
theme: màu đỏ
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, thiết kế-1, lập trình-0, Phys-comp-0, sản xuất-0, cộng đồng-0
description: Tạo một trang web tạp chí nhiều trang.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: nghệ thuật
technologies: html-css-javascript
site_areas: dự án
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Tiêu đề và nền
  - 
    title: Tạo cột
  - 
    title: Mục tạp chí phong cách
  - 
    title: 'Thách thức: Thêm các mục vào cột bên trái'
  - 
    title: Thêm một trang thứ hai
  - 
    title: 'Thách thức: Thêm một liên kết trở lại trang đầu tiên'
  - 
    title: 'Thử thách: Điền vào trang thứ hai của bạn'
  - 
    title: Thêm một hình ảnh động
  - 
    title: 'Thử thách: Thêm một hình ảnh động khác'
