---
title: Revista
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Criar um site de revistas multi-páginas.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - title: Introdução
  - title: Cabeçalho e Fundo
  - title: Criar Colunas
  - title: Itens de Estilo da Revista
  - title: 'Desafio: Adicionar itens à coluna esquerda'
  - title: Adicionar uma segunda página
  - title: 'Desafio: Adicionar um link para voltar à primeira página'
  - title: 'Desafio: Preencher a tua segunda página'
  - title: Adicionar uma animação
  - title: 'Desafio: Adicionar outra animação'
