---
title: Zeitschrift
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Erstelle eine Zeitschriften-Webseite mit mehreren Seiten.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: Kunst
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Überschrift und Hintergrund
  - 
    title: Spalten erstellen
  - 
    title: Zeitschriftenartikel grafisch gestalten
  - 
    title: 'Aufgabe: Füge Posten in der linken Spalte hinzu'
  - 
    title: Eine zweite Seite hinzufügen
  - 
    title: 'Aufgabe: Füge einen Link zurück zur ersten Seite ein'
  - 
    title: 'Aufgabe: Fülle deine zweite Seite'
  - 
    title: Eine Animation hinzufügen
  - 
    title: 'Aufgabe: Füge eine weitere Animation hinzu'
