---
title: Revistă
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Creează un website pentru o revistă cu mai multe pagini.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Titlu și fundal
  - 
    title: Crearea coloanelor
    completion:
      - engaged
  - 
    title: Stilizează elementele revistei
  - 
    title: 'Provocare: Adaugă elemente în coloana stângă'
  - 
    title: Adaugă o a doua pagină
  - 
    title: 'Provocare: Adaugă un link înapoi către prima pagină'
  - 
    title: 'Provocare: Umple a doua pagină'
  - 
    title: Adaugă o animație
    completion:
      - internal
  - 
    title: 'Provocare: Adaugă altă animație'
