---
title: Revista
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Neste projeto, você vai aprender a usar HTML e CSS para criar um website em formato de revista, com um layout de duas páginas.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: arte
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Revista
  - 
    title: Cabeçalho e plano de fundo
  - 
    title: Criando colunas
  - 
    title: Itens de estilo da revista
  - 
    title: 'Desafio: Adicionando itens na coluna a esquerda'
  - 
    title: Adicionando a segunda página
  - 
    title: 'Desafio: Adicionando um link na primeira página'
  - 
    title: 'Desafio: Preencha sua segunda página'
  - 
    title: Adicionando uma animação
  - 
    title: 'Desafio: Adicionando outra animação'
