---
title: Revista
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crea un sitio web con una revista de varias páginas.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - title: Introducción
  - title: Encabezado y fondo
  - title: Crear columnas
  - title: Dar estilo a las secciones de la revista
  - title: 'Desafío: añade elementos en la columna izquierda'
  - title: Añade otra página
  - title: 'Desafío: añade un enlace que te devuelva a la primera página'
  - title: 'Desafío: completa la segunda página'
  - title: Añade animación
  - title: 'Desafío: agrega otra animación'
