---
title: Časopis
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Izradi veb-sajt časopisa koji ima više stranica.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
  completion: engaged
- title: Naslov i pozadina
- title: Kreiranje kolona
- title: Stilizuj objekte časopisa
- title: 'Izazov: Dodaj objekte u lijevu kolonu'
- title: Dodaj drugu stranicu
- title: 'Izazov: Dodaj link za povratak na prvu stranicu'
- title: 'Izazov: Popuni drugu stranicu'
- title: Dodaj animaciju
  completion: internal
- title: 'Izazov: Dodaj još jednu animaciju'
