---
title: Magazine
hero_image: images/magazine.png
theme: rouge
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programmation-0, phys-comp-0, fabrication-0, communauté-0
description: Créer un site Web magazine à plusieurs pages.
original_url: https://codeclubprojects.org/fr-FR/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projets
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introduction
  - 
    title: En-tête et arrière-plan
  - 
    title: Créer des colonnes
  - 
    title: Styliser les objets du magazine
  - 
    title: 'Défi : Ajouter des objets à la colonne de gauche'
  - 
    title: Ajouter une seconde page
  - 
    title: 'Défi : Ajouter un lien de retour à la première page'
  - 
    title: 'Défi : Remplir votre seconde page'
  - 
    title: Ajouter une animation
  - 
    title: 'Défi : Ajouter une autre animation'
