---
title: Magazine
hero_image: images/magazine.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Créer un site Web magazine à plusieurs pages.
original_url: https://codeclubprojects.org/en-GB/webdev/magazine
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: En-tête et arrière-plan
- title: Créer des colonnes
  completion:
  - engaged
- title: Styliser les éléments du magazine
- title: 'Défi : Ajouter des éléments à la colonne de gauche'
- title: Ajouter une seconde page
- title: 'Défi : Ajouter un lien de retour à la première page'
- title: 'Défi : Remplir ta seconde page'
- title: Ajouter une animation
  completion:
  - internal